site_name: 我的笔记
site_url: https://13757539485.github.io/note/

nav: 
- Android系统:
    - 学习笔记: 
        - Java: 
           - 基础: android/java/java_basic.md
           - 虚拟机: android/java/java_jvm.md
           - 泛型: android/java/java_genericity.md
           - 反射: android/java/java_reflex.md
        - Kotlin: 
           - 入门: android/kotlin/kotlin_basic.md
           - 函数: android/kotlin/kotlin_function.md
           - 操作符与关键字: android/kotlin/kotlin_op.md
           - 集合: android/kotlin/kotlin_collection.md
           - 类: android/kotlin/kotlin_class.md
           - 实战应用: android/kotlin/kotlin_code.md
           - 原理: android/kotlin/kotlin_principle.md
        - 数据结构: android/java/java_collection.md
        - 设计模式: android/design_mode.md
        - 并发编程:
           - 基础概念: android/java/java_base.md
           - 线程: android/java/java_thread.md
           - 线程安全: android/java/java_safe.md
           - 锁: android/java/java_lock.md
        - 网络编程: 
           - 网络基础: android/network/net_base.md
           - 抓包工具: android/network/net_charles.md
        - 高级UI: 
           - RecycleView: android/ui/ui_recyclerview.md
           - View: android/android_ui.md
        - Framework:
           - IPC通信: android/fws/fws_process.md
        - 性能优化: 
           - 图片相关: android/performance/android_bitmap.md
           - 数据结构: android/performance/android_datastructure.md
        - 插件化技术: android/android_hotfix.md
        - 开源框架: android/android_github.md
        - 开发模式: android/android_dev_mode.md
        - Apk相关: android/android_build_apk.md
        - Compose: android/android_compose.md
        # - NDK: android/android_ndk.md
        - Flutter: android/android_flutter.md
        # - 小程序: android/android_wechat.md
    - 玩机家族:
        - OS大全: android/android_os.md
        - Root面具: android/android_root.md
- Window系统: 
    - 系统安装: window/window_install.md
    - 常见软件: window/window_software.md
    - 实用教程: 
        - VMWare安装: window/window_vmware.md
        - WSL2: window/window_wsl2.md
        - Android子系统: window/window_inner_android.md
        - Window11相关: window/window_win11.md
- Linux系统: 
    - 推荐系统: 
        - ubuntu: linux/ubuntu_install.md
        - deepin: linux/deepin_install.md
    - 常见软件: linux/linux_software.md
    - 实用教程: 
        - 常用命令: linux/linux_command.md
- mac系统: 
    - 黑苹果: mac/mac_install.md
    - 使用软件: mac/mac_software.md
    - SwiftUI: mac/mac_swift.md
- OpenHarmony系统:
    - 源码编译: ohos/ohos_build.md
    - ArkUI开发: ohos/arkui.md
- 常见开发环境: 
    - python部署: python.md
    - git部署: git_github.md
- 其他学习: 
    - Excel: excel.md
    - Markdown: markdown.md
theme: 
  name: material
  language: zh
  palette:
    - scheme: default
      primary: light blue
      accent: cyan
      toggle:
        icon: material/brightness-7 
        name: 开启深色模式
    - scheme: slate
      primary: light grey 
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: 关闭深色模式
  features:
    - navigation.tabs
    - search.suggest   # 搜索输入一些字母时推荐补全整个单词
    - search.highlight   # 搜索出的文章关键词加入高亮
  font:
    text: Microsoft YaHei
    code: Courier New

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra:
  search:
    language: 'en,zh,jp'
  generator: false  #删除页脚显示“使用 MkDocs 材料制造”
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/13757539485

plugins:
  - search

copyright: Copyright &copy; 2023俞梨 # 左下角的版权声明